---
title: "OHI_Presentation"
author: "Patricia Faundez"
date: "August 19, 2016"
output:
  html_document:
    toc: true
    toc_depth: 4
---

```{r}

Abstract
There are three fundamental questions we must be able to answer to effectively manage wildlife populations: (1) what is the baseline size of the population? (2) how has the size of the population changed? and (3) how vulnerable is the population to exploitation? It follows from this that we cannot effectively manage the marine environment without knowledge of what it looked like in a pristine state, but human impacts have wreaked such havoc on the ocean that it is often impossible to accurately characterize marine populations pre-exploitation. I use the unique setting of Palmyra Atoll, a remote U.S. National Wildlife Refuge in the central Pacific Ocean, to describe the population dynamics, ecological characteristics, and behavior of reef sharks absent significant human impacts. I use a combination of extensive field sampling and spatially explicit analytical tools to resolve a set of ecological debates regarding the trophic structure of coral reef communities, the drivers of life history variability, and the ecological effects of non-consumptive human impacts on marine predators. Ultimately, I will show that even healthy predator populations may be more precarious than previously thought, but that humans can interact with marine predators with minimal behavioral repercussions.

```


#title: "KUNI FELLOWSHIP PROPOSAL"
author: "Patricia Faundez"
date: "February 17, 2016"
output:
  html_document:
    toc: true
    toc_depth: 4

####Maping mariculture harvest in the world (data from, https://github.com/OHI-Science/ohi-global)

```{r, echo=FALSE, warning=FALSE}

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(knitr)
})

```


# The Geo chart is displayed in a window's browser when you run this chunk

```{r Maping IUCN Category Index per Country}

#run this chunk to get the Geo chart

setwd("~/Winter_2016/Environmental_Informatics/marinehealth.github.io/KUNI")

mar_harvest <- read_csv(file="mar_harvest_tonnes.csv")     #read cvs always as read_csv (instead of read.csv) it keep the data without factors

#This is the file with thae matching column "FAO_Country"
conversion <- read_csv(file="CountryConversion.csv")


harvest_countries = mar_harvest %>%           
  rename(FAO_Country=country) %>%             #rename match column FAO_Country
  left_join(                                  #joining harvest_countries with conversion data 
    conversion, 
    by = c("FAO_Country")) 
str(harvest_countries)
  
harvest_2013 = harvest_countries %>%                     
  filter(year > 2012)%>%                           # filtering to keep only 2013 year of harvest
  group_by(FAO_Country) %>%                        #grouping by country
   summarise(
     harvest = round(sum(value),digits=1), n_species = n()) #getting sum per country and n species harvested

# Plot countries, I am using the sum of all species for country as an example that we want to show in this map

suppressWarnings(suppressMessages(library(googleVis))) #install.packages("googleVis")

#### Create a geo chart
#harvest in all countries
G1 <- gvisGeoChart(harvest_2013, "FAO_Country", "harvest", hovervar="FAO_Country",
                options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G1)

#number of species produced since 1950
G2 <- gvisGeoChart(harvest_2013, "FAO_Country", "n_species", hovervar="FAO_Country",
                options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G2)

```

```{r}
#harvest in all countries without China  
harvest_2013_noChina = harvest_countries %>%                     
  filter(year > 2012)%>%                           # filtering to keep only 2013 year of harvest
  filter(FAO_Country != "China")%>% 
  group_by(FAO_Country) %>%                        #grouping by country
   summarise(
     harvest = round(sum(value),digits=1), n_species = n()) #getting sum per country and n species harvested

# Plot countries, I am using the sum of all species for country as an example that we want to show in this map

suppressWarnings(suppressMessages(library(googleVis))) #install.packages("googleVis")

#### Create a geo chart

G3 <- gvisGeoChart(harvest_2013_noChina, "FAO_Country", "harvest", hovervar="FAO_Country",
                options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G3)


```

```{r}
#number of species with harvest > 1 ton in year 2013 
species_2013_no0 = harvest_2013 %>%
  filter(harvest != 0)%>%                           # filtering to keep only 2013 year of harvest
  group_by(FAO_Country) %>%                        #grouping by country
   summarise(
     harvest = round(sum(harvest),digits=1), n_species = n()) #getting sum per country and n species harvested

# Plot countries, I am using the sum of all species for country as an example that we want to show in this map

suppressWarnings(suppressMessages(library(googleVis))) #install.packages("googleVis")

#### Create a geo chart

G4 <- gvisGeoChart(species_2013_no0, "FAO_Country", "n_species", hovervar="FAO_Country",
                options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G4)


```

```{r}
#number of species in 2013 with havest >10000 ton
species_2013_10000harvest = harvest_countries %>% 
  filter(year > 2012)%>% 
  filter(value > 10000)%>%                           # filtering to keep only 2013 year of harvest
  group_by(FAO_Country) %>%                        #grouping by country
   summarise(
     harvest = round(sum(value),digits=1), n_species = n()) #getting sum per country and n species harvested

# Plot countries, I am using the sum of all species for country as an example that we want to show in this map

suppressWarnings(suppressMessages(library(googleVis))) #install.packages("googleVis")

#### Create a geo chart

G5 <- gvisGeoChart(species_2013_10000harvest, "FAO_Country", "n_species", hovervar="FAO_Country",
                options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G5)


```