---
title: "Fisheries Chile"
author: "Patricia Faundez"
date: "September 6, 2016"
output: html_document
---
# EXPLORATORY DATA ANALYSIS
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#pkgs <- c(
  # "dplyr", "gapminder", "ggplot2", "jsonlite", "Lahman", 
  #"lubridate", "modelr", "nycflights13", "purrr", "readr", 
  #"stringr", "tibble", "tidyr"
#)
#install.packages(pkgs)

```

# INDUSTRIAL, SHIP OWNER AND ARTISANAL LANDINGS 2000-2014 
```{r}
setwd("~/OHI_Chile/Analysis_R/OHI-Chile-by-Regions.github.io/fisheries")

library(readr)

#If we need to be explicit about where a function (or dataset) comes from, we will use the special form package::function(). For example, ggplot2::ggplot() tells you explicitly that we are using the ggplot() function from the ggplot2 package.

#Reading Industrial landings and Artisanal+Ship Owner landings

INDUSTRY <- read_csv("~/OHI_Chile/Analysis_R/OHI-Chile-by-Regions.github.io/fisheries/industrial.csv")

print(INDUSTRY)

#Reading Artisanal+Ship Owner landings

ARTISANAL <- read_csv("~/OHI_Chile/Analysis_R/OHI-Chile-by-Regions.github.io/fisheries/artisanal.csv")

print(ARTISANAL)

```



```{r}

library(tidyr)
library(dplyr)
library(ggplot2)

#Industrial landings tidy 

INDUSTRY <- gather(INDUSTRY, "year", "landings", 4:18)
print(INDUSTRY) # is giving year as chr

#Artisanal + Ship Owner landings tidy 

ARTISANAL <- gather(ARTISANAL, "year", "landings", 4:18)
print(ARTISANAL) # is giving year as chr

#merging Industry + Artisanal landings datasets
 catch <- dplyr::bind_rows(INDUSTRY, ARTISANAL)
View(catch)
#Getting a sum for the total landings in Chile per year
  catch_sum <- catch %>%
  group_by(year) %>%
  summarise(sum = sum(landings, na.rm = TRUE)) 
    View(catch_sum)
    
## scatterplot of total landings per year     
ggplot(catch_sum, aes(x = year, y = sum)) +
  geom_point(size = 4, shape = 15, alpha = 0.3)

#scatterplot of total landings per year made with better code
catch %>%
  group_by(year) %>%
  summarise(sum = sum(landings, na.rm = TRUE)) %>%
  ggplot(aes(year, sum)) +
  theme_bw() +
  geom_point(alpha = 1, color = 'blue', size = 5) + #changing point size, shape, color
  labs(x = 'Time (year)', y = "Landings (ton)", title = "Chile Total landings (Industry + Artisanal") 

write_csv(catch, "Chile_total_catch.csv")

write_csv(catch_sum, "Chile_catch_year_sum.csv")

#ONLY ARTISANAL

ARTISANAL %>%
  group_by(year) %>%
  summarise(sum = sum(landings, na.rm = TRUE)) %>%
  ggplot(aes(year, sum)) +
  theme_bw() +
  geom_point(alpha = 1, color = 'blue', size = 5) + #changing point size, shape, color
  labs(x = 'Time (year)', y = "Landings (ton)", title = "Chile Artisanal Fisheries Landings") 

#ONLY INDUSTRY

INDUSTRY %>%
  group_by(year) %>%
  summarise(sum = sum(landings, na.rm = TRUE)) %>%
  ggplot(aes(year, sum)) +
  theme_bw() +
  geom_point(alpha = 1, color = 'blue', size = 5) + #changing point size, shape, color
  labs(x = 'Time (year)', y = "Landings (ton)", title = "Chile Industry Fisheries Landings") 


```


INDUSTRIAL 
```{r}
#install.packages("ggplot2")
library(ggplot2)

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings, color = stock)) #por especie y agrupar por region

ggplot(data = FIS_Artisanal_ShipOwner) + 
  geom_point(mapping = aes(x = year, y = landings, color = stock)) #hacer un grafico mezclando industrial + artesanal

ggplot(FIS_industry) + 
  geom_point(mapping = aes(x = rgn_id, y = stock, size = landings))

ggplot(FIS_Artisanal_ShipOwner) + 
  geom_point(mapping = aes(x = rgn_id, y = stock, size = landings))

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_wrap(~ stock, nrow = 2)

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_wrap(~ stock)

ggplot(data = FIS_Artisanal_ShipOwner) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_wrap(~ stock, nrow = 2)

ggplot(data = FIS_Artisanal_ShipOwner) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_wrap(~ stock)

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_grid(rgn_id ~ stock)

ggplot(data = FIS_Artisanal_ShipOwner) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_grid(rgn_id ~ stock)

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_grid(rgn_id ~ .)

ggplot(data = FIS_industry) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_grid(. ~ stock)

  
    
    FIS_industry_Anchovy <- FIS_industry %>% 
      filter(stock == 'ANCHOVETA')
    
    ggplot(data = FIS_industry_Anchovy) + 
  geom_point(mapping = aes(x = year, y = landings, color = rgn_id))
  

    ggplot(data = FIS_industry_Anchovy) + 
  geom_point(mapping = aes(x = rgn_id , y = landings, color = year))
    
    ggplot(data = FIS_industry_Anchovy) + 
  geom_point(mapping = aes(x = year, y = landings)) + 
  facet_grid(. ~ rgn_id)

ggplot(data = FIS_industry_Anchovy) +
  geom_smooth(mapping = aes(x = year, y = landings, group = rgn_id))

ggplot(data = FIS_industry_Anchovy) +
  geom_bar(mapping = aes(x = rgn_id))

ggplot(data = FIS_industry_Anchovy, mapping = aes(x = rgn_id)) +
  geom_histogram(binwidth = 0.1)
    

library(tidyr)
library(ggplot2)

   catch <- dplyr::bind_rows(FIS_industry, FIS_Artisanal_ShipOwner)

  catch %>%
  group_by(year) %>%
  summarise(sum = sum(landings, na.rm = TRUE)) %>%
  ggplot(aes(year, sum)) +
  theme_bw() +
  geom_point(alpha = 1, color = 'blue', size = 5)
View(catch)


```


```{r}



```


STOCK ASSESSMENT DATA WRANGLING

```{r}
#creating layer FIS_scores.csv

#Creating a Data Frame from Scratch in R using the data.frame() function. Making a data frame from vectors in R. So, letâs make a data frame with the region_id,	stock, year,	metric and	score. First, I create five vectors that contain the necessary informations:

#region_id <- c("XV", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "XIV", "X", "XI", "XII")
#stock <- c('ANCHOVETA', 'CAMARON NAILON', 'CONGRIO DORADO', 'JUREL', 'LANGOSTINO AMARILLO', 'LANGOSTINO COLORADO', 'MERLUZA COMUN', 'MERLUZA DE COLA', 'MERLUZA DEL SUR O AUSTRAL', 'SARDINA COMUN', 'RAYA VOLANTIN')
#year <- c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014)
#metric <- c('bbmsy', 'ffmsy')
#score <- c()

#By default, R always transforms character vectors to factors when creating a data frame with character vectors or converting a character matrix to a data frame. This can be a nasty cause of errors in your code if youâre not aware of it. If you make it a habit to always specify the stringsAsFactors argument, you can avoid a lot of frustration. USE: employ.data <- data.frame(employee, salary, startdate, stringsAsFactors=FALSE)


```

